Traceback (most recent call last):
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\pj\anaconda3\envs\flowing\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\pj\anaconda3\envs\flowing\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
barcelona = paminco.net.Network.from_xml(REL_DIR + "data/traffic/Barcelona.xml")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_8532/2419181191.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mbarcelona[0m [1;33m=[0m [0mpaminco[0m[1;33m.[0m[0mnet[0m[1;33m.[0m[0mNetwork[0m[1;33m.[0m[0mfrom_xml[0m[1;33m([0m[0mREL_DIR[0m [1;33m+[0m [1;34m"data/traffic/Barcelona.xml"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\git\paminco\paminco\net\network.py[0m in [0;36mfrom_xml[1;34m(cls, file, return_dict, **kwargs)[0m
[0;32m   1584[0m             [0;31m`[0m[0;31m`[0m[0mfrom_xml[0m[0;31m`[0m[0;31m`[0m [0mmethod[0m [0mof[0m [0mNetworkCost[0m [1;32mclass[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1585[0m         """
[1;32m-> 1586[1;33m         [0medge_data[0m [1;33m=[0m [0mEdges[0m[1;33m.[0m[0mfrom_xml[0m[1;33m([0m[0mfile[0m[1;33m,[0m [0mreturn_data[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1587[0m         [0mnode_data[0m [1;33m=[0m [0mNodes[0m[1;33m.[0m[0mfrom_xml[0m[1;33m([0m[0mfile[0m[1;33m,[0m [0mreturn_data[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1588[0m         [0mdemand_data[0m [1;33m=[0m [0mfile[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\git\paminco\paminco\net\shared.py[0m in [0;36mfrom_xml[1;34m(cls, data, return_data, **kwargs)[0m
[0;32m    436[0m             [1;33m**[0m[0mkwargs[0m[1;33m[0m[1;33m[0m[0m
[0;32m    437[0m             ):
[1;32m--> 438[1;33m         [0mdata[0m [1;33m=[0m [0mxml_find_root[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    439[0m         [0medges[0m [1;33m=[0m [0mdata[0m[1;33m.[0m[0mfind[0m[1;33m([0m[1;34m"edges"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    440[0m         [1;32mif[0m [0medges[0m [1;32mis[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\git\paminco\paminco\utils\readin.py[0m in [0;36mxml_find_root[1;34m(data, root_tag)[0m
[0;32m    157[0m     [1;32mif[0m [0misinstance[0m[1;33m([0m[0mdata[0m[1;33m,[0m [0mstr[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    158[0m         [1;32mif[0m [0mdata[0m[1;33m.[0m[0mendswith[0m[1;33m([0m[1;34m".xml"[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 159[1;33m             [0mdata[0m [1;33m=[0m [0met[0m[1;33m.[0m[0mparse[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    160[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    161[0m             [0mdata[0m [1;33m=[0m [0met[0m[1;33m.[0m[0mfromstring[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\pj\anaconda3\envs\flowing\lib\xml\etree\ElementTree.py[0m in [0;36mparse[1;34m(source, parser)[0m
[0;32m   1200[0m     """
[0;32m   1201[0m     [0mtree[0m [1;33m=[0m [0mElementTree[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1202[1;33m     [0mtree[0m[1;33m.[0m[0mparse[0m[1;33m([0m[0msource[0m[1;33m,[0m [0mparser[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1203[0m     [1;32mreturn[0m [0mtree[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1204[0m [1;33m[0m[0m

[1;32mc:\users\pj\anaconda3\envs\flowing\lib\xml\etree\ElementTree.py[0m in [0;36mparse[1;34m(self, source, parser)[0m
[0;32m    582[0m         [0mclose_source[0m [1;33m=[0m [1;32mFalse[0m[1;33m[0m[1;33m[0m[0m
[0;32m    583[0m         [1;32mif[0m [1;32mnot[0m [0mhasattr[0m[1;33m([0m[0msource[0m[1;33m,[0m [1;34m"read"[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 584[1;33m             [0msource[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0msource[0m[1;33m,[0m [1;34m"rb"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    585[0m             [0mclose_source[0m [1;33m=[0m [1;32mTrue[0m[1;33m[0m[1;33m[0m[0m
[0;32m    586[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../../../../../data/traffic/Barcelona.xml'
FileNotFoundError: [Errno 2] No such file or directory: '../../../../../data/traffic/Barcelona.xml'

